import { desc, eq, sql } from "drizzle-orm";
import { NativeLink as Link } from "../native-link";
import { getDb } from "../../db";
import { professionalProfiles, reportCorrections, reports } from "../../db/schema";
import { requireVHF14Admin } from "../chatgpt-auth";
import { ReviewButtons } from "./review-buttons";
import { CorrectionReviewButtons } from "./correction-review-buttons";
import { ProfileReviewButtons } from "./profile-review-buttons";

export const dynamic="force-dynamic";
type Report=typeof reports.$inferSelect;
const eventOrder=["Anchor Dropped","Anchor Aweigh","Pilot on Board","Tugs Connected","First Line","All Fast","Gangway Down","Cargo Operations Started","Cargo Operations Completed","Vessel Ready to Sail","Shifting Started","Shifting Completed","Last Line","Pilot Off","Port Clear"];
function callKey(report:Report){return report.portCallId||`legacy:${report.imo}|${report.portCode}`}
function tolerance(event:string){return event.startsWith("Cargo ")||event==="Vessel Ready to Sail"||event==="Gangway Down"?10:5}
function minutes(value:string){return Date.parse(`${value}Z`)/60000}

export default async function Admin({searchParams}:{searchParams:Promise<{q?:string;port?:string;status?:string;sort?:string}>}){
 await requireVHF14Admin("/admin");const params=await searchParams;const q=(params.q??"").trim().toLowerCase();const port=(params.port??"").trim().toUpperCase();const status=params.status??"pending";const sort=params.sort??"attention";const db=getDb();
 const rows=(await db.select().from(reports).orderBy(desc(reports.createdAt)).limit(500)).map(report=>report.eventType==="Pilot Away"?{...report,eventType:"Pilot Off"}:report);
 const corrections=await db.select().from(reportCorrections).where(eq(reportCorrections.status,"pending")).orderBy(desc(reportCorrections.createdAt)).limit(100);
 const profiles=await db.select().from(professionalProfiles).orderBy(desc(professionalProfiles.updatedAt)).limit(500);const profileByUser=new Map(profiles.map(profile=>[profile.userId,profile]));
 const statusTotals=await db.select({status:reports.status,count:sql<number>`count(*)`}).from(reports).groupBy(reports.status);const totalFor=(name:string)=>Number(statusTotals.find(item=>item.status===name)?.count??0);
 const pendingProfiles=profiles.filter(profile=>profile.status==="pending"||profile.organisationStatus==="pending");const reportsById=new Map(rows.map(report=>[report.id,report]));
 const matches=(report:Report)=>(status==="all"||report.status===status)&&(!port||report.portCode===port)&&(!q||`${report.vesselName} ${report.imo} ${report.portCode} ${report.eventType} ${report.reporterEmail??""} ${report.organisation}`.toLowerCase().includes(q));
 const matchingCalls=new Set(rows.filter(matches).map(callKey));const calls=new Map<string,Report[]>();for(const report of rows)if(matchingCalls.has(callKey(report)))calls.set(callKey(report),[...(calls.get(callKey(report))??[]),report]);
 const grouped=[...calls.entries()].map(([id,items])=>({id,items:[...items].sort((a,b)=>a.eventTimeUtc.localeCompare(b.eventTimeUtc)),pending:items.filter(item=>item.status==="pending"),latest:items.reduce((latest,item)=>item.createdAt>latest?item.createdAt:latest,"")})).sort((a,b)=>sort==="latest"?b.latest.localeCompare(a.latest):(b.pending.length-a.pending.length||a.items[0].eventTimeUtc.localeCompare(b.items[0].eventTimeUtc))).slice(0,60);
 const pendingCallCount=new Set(rows.filter(report=>report.status==="pending").map(callKey)).size;
 return <main className="admin adminConsole">
  <header><Link href="/account">← My account</Link><div><p className="kicker">ADMIN CONSOLE</p><h1>Operational verification</h1><p>Work by vessel call: review every milestone, source and conflict without jumping between separate entries.</p></div></header>
  <section className="adminMetrics"><article><span>PENDING CALLS</span><b>{pendingCallCount}</b></article><article><span>PENDING REPORTS</span><b>{totalFor("pending")}</b></article><article><span>CORRECTIONS</span><b>{corrections.length}</b></article><article><span>PROFILE REVIEWS</span><b>{pendingProfiles.length}</b></article></section>
  <nav className="adminJump" aria-label="Work queues"><a href="#port-calls">Port calls</a><a href="#profiles">Profiles {pendingProfiles.length>0&&<b>{pendingProfiles.length}</b>}</a><a href="#corrections">Corrections {corrections.length>0&&<b>{corrections.length}</b>}</a><Link href="/admin/audit">Audit log</Link></nav>
  <section id="port-calls" className="adminWorkSection"><div className="sectionTitle"><div><p className="kicker">VESSEL-CENTRED QUEUE</p><h2>Port calls</h2></div><span>{grouped.length} calls shown · latest 500 reports considered</span></div>
   <form className="adminFilters"><input name="q" defaultValue={params.q} placeholder="Vessel, IMO, event, source or email"/><input name="port" defaultValue={params.port} placeholder="Port UN/LOCODE" maxLength={5}/><select name="status" defaultValue={status}><option value="pending">Calls requiring review</option><option value="verified">Calls with verified reports</option><option value="rejected">Calls with rejected reports</option><option value="all">All recent calls</option></select><select name="sort" defaultValue={sort}><option value="attention">Most pending first</option><option value="latest">Latest submissions first</option></select><button>Apply</button><Link href="/admin">Clear</Link></form>
   <div className="callReviewList">{grouped.map(call=>{const first=call.items[0];const eventGroups=new Map<string,Report[]>();for(const report of call.items)eventGroups.set(report.eventType,[...(eventGroups.get(report.eventType)??[]),report]);const locations=[...new Set(call.items.flatMap(item=>[item.terminal,item.berth,item.pilotBoardingPlace]).filter(Boolean))];return <article className="callReviewCard" key={call.id}>
    <header><div><span className={call.pending.length?"attentionFlag":"completeFlag"}>{call.pending.length?`${call.pending.length} pending`:"No pending reports"}</span><h2>{first.vesselName} <small>IMO {first.imo}</small></h2><p>{first.portCode}{locations.length?` · ${locations.join(" · ")}`:""} · Call {call.id.slice(0,8)}</p></div><div className="callSummary"><b>{eventGroups.size}</b><span>milestones</span><b>{new Set(call.items.map(item=>item.reporterUserId??`report-${item.id}`)).size}</b><span>sources</span></div></header>
    {call.pending.length>1&&<aside className="callBulk"><span>All pending reports in this call can be reviewed together when the evidence supports the same decision.</span><ReviewButtons ids={call.pending.map(item=>item.id)} label={`${first.vesselName} call`}/></aside>}
    <div className="callEventList">{[...eventGroups.entries()].sort(([a],[b])=>(eventOrder.indexOf(a)<0?99:eventOrder.indexOf(a))-(eventOrder.indexOf(b)<0?99:eventOrder.indexOf(b))).map(([event,items])=>{const sourceCount=new Set(items.map(item=>item.reporterUserId??`report-${item.id}`)).size;const times=items.map(item=>minutes(item.eventTimeUtc));const spread=Math.max(...times)-Math.min(...times);const conflict=items.length>1&&spread>tolerance(event);return <section className="eventReview" key={event}><div className="eventReviewHead"><div><h3>{event}</h3><span>{sourceCount} source{sourceCount===1?"":"s"} · tolerance {tolerance(event)} min</span></div>{items.length>1&&<b className={conflict?"conflictFlag":"agreementFlag"}>{conflict?`${spread} min conflict`:`${spread} min agreement`}</b>}</div>{items.map(item=>{const profile=item.reporterUserId?profileByUser.get(item.reporterUserId):undefined;return <div className="reportEntry" key={item.id}><div className="reportTime"><b>{item.eventTimeUtc.replace("T"," ")}</b><span>UTC · {item.timeBasis}</span></div><div className="reportSource"><b>{item.sourceRole}{item.organisation?` · ${item.organisation}`:""}</b><span>{item.reporterEmail??"No email"} · profile <i className={`status ${profile?.status??"pending"}`}>{profile?.status??"not created"}</i>{profile?.participationType==="organisation"?` · organisation ${profile.organisationStatus}`:""}</span>{item.notes&&<small>{item.notes}</small>}</div><span className={`status ${item.status}`}>{item.status}</span>{item.status==="pending"?<ReviewButtons id={item.id}/>:<small className="reviewedMeta">{item.reviewedAt?`Reviewed ${item.reviewedAt}`:""}</small>}</div>})}</section>})}</div>
   </article>})}{!grouped.length&&<p className="empty">No port calls match these filters.</p>}</div>
  </section>
  <section id="profiles" className="adminWorkSection"><div className="sectionTitle"><div><p className="kicker">IDENTITY QUEUE</p><h2>Professional profiles</h2></div><Link href="/admin/users">Open user directory →</Link></div>{pendingProfiles.length?<div className="profileQueue">{pendingProfiles.map(profile=><article key={profile.id}><div><span className={`status ${profile.status}`}>professional · {profile.status}</span>{profile.participationType==="organisation"&&<span className={`organisationStatus status ${profile.organisationStatus}`}>organisation · {profile.organisationStatus}</span>}<h2>{profile.fullName}</h2><p>{profile.jobTitle} · {profile.professionalRole.toUpperCase()} · {profile.portScope} · {profile.country}</p><small>{profile.email}{profile.organisation?` · ${profile.organisation}`:""}</small>{profile.verificationNotes&&<p className="reviewNotes"><b>Verification:</b> {profile.verificationNotes}</p>}</div><div className="reviewGroups">{profile.status==="pending"&&<section><span>PROFESSIONAL</span><ProfileReviewButtons id={profile.id} subject="professional"/></section>}{profile.participationType==="organisation"&&profile.organisationStatus==="pending"&&<section><span>ORGANISATION</span><ProfileReviewButtons id={profile.id} subject="organisation"/></section>}</div></article>)}</div>:<p className="empty">No professional profiles require review.</p>}</section>
  <section id="corrections" className="adminWorkSection"><div className="sectionTitle"><div><p className="kicker">CHANGE CONTROL</p><h2>Correction requests</h2></div></div>{corrections.length?<div className="correctionQueue">{corrections.map(correction=>{const original=reportsById.get(correction.reportId);const proposed=JSON.parse(correction.proposedData) as typeof original;return <article key={correction.id}><div><span className="status pending">pending correction</span><h2>{original?.vesselName??`Report #${correction.reportId}`}</h2><p><b>Current:</b> {original?.portCode} · {original?.eventType} · {original?.eventTimeUtc.replace("T"," ")} UTC</p><p><b>Proposed:</b> {proposed?.portCode} · {proposed?.eventType} · {proposed?.eventTimeUtc.replace("T"," ")} UTC</p><p className="reviewNotes"><b>Reason:</b> {correction.reason}</p></div><CorrectionReviewButtons id={correction.id}/></article>})}</div>:<p className="empty">No correction requests require review.</p>}</section>
 </main>
}
