"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Anchor, Boxes, FileText, Search, Ship, TowerControl, Users } from "lucide-react";
import { localTimeToUtc, portTimezones, shortTime, timezoneOffsetLabel, utcToPortTime } from "../lib/port-time";

type EventState="actual"|"current"|"estimated"|"planned"|"pending"|"reported";
type AnchorageContext={label:string;detail:string;status:"REPORTED"|"VERIFIED"};
type PortCall={id:string;vessel:string;imo:string;port:string;portName:string;timezone?:string;locationContext?:string;stage:"anchorage"|"inbound"|"alongside"|"shifting"|"outbound";activity:string;confidence:string;confidenceLabel:string;source:"live"|"demo";anchorage?:AnchorageContext;events:[string,string,EventState,string?,number?,string?,boolean?,boolean?][]};
type LiveReport={id:number;ownReportId?:number;portCallId:string;vesselName:string;imo:string;portCode:string;eventType:string;eventTimeUtc:string;eventTimeOriginal:string;timeReference:"port_local"|"utc";portTimezone:string;timeBasis:"actual"|"estimated"|"planned";terminal:string;berth:string;pilotBoardingPlace:string;status:"pending"|"verified";createdAt:string;independentSources:number;timeSpreadMinutes:number;corroborated:boolean};
type PortOption={code:string;name:string;country:string;countryName:string;subdivision:string;timezone:string;latitude:number|null;longitude:number|null;source:string};
type QuickTarget={reportId?:number;vessel:string;imo:string;port:string;portName:string;timezone:string;eventName:string;state:EventState;eventTimeUtc?:string;isOwn?:boolean;verified?:boolean};

const demoCalls:PortCall[]=[
 {id:"demo-aurora",vessel:"MSC AURORA",imo:"9839272",port:"ESVLC",portName:"Valencia",stage:"alongside",activity:"Cargo operations",confidence:"96/100",confidenceLabel:"DEMO CONFIDENCE",source:"demo",events:[["Pilot on Board","13:14","actual"],["Tugs Connected","13:31","actual"],["First Line","13:52","actual"],["All Fast","14:08","actual"],["Gangway Down","14:19","actual"],["Cargo Ops Started","14:47","current"],["Cargo Ops Completed","EST 22:30","estimated"],["Port Clear","EST 23:45","estimated"]]},
 {id:"demo-lima",vessel:"MAERSK LIMA",imo:"9720196",port:"NLRTM",portName:"Rotterdam",stage:"anchorage",activity:"At anchorage",confidence:"88/100",confidenceLabel:"DEMO CONFIDENCE",source:"demo",anchorage:{label:"AT ANCHORAGE",detail:"Since 14:05 UTC",status:"REPORTED"},events:[["Pilot on Board","EST 16:58","current"],["Tugs Connected","EST 17:08","estimated"],["First Line","EST 17:18","estimated"],["All Fast","EST 17:25","estimated"],["Gangway Down","—","pending"],["Cargo Ops Started","—","pending"],["Cargo Ops Completed","—","pending"],["Port Clear","—","pending"]]},
 {id:"demo-oceanic",vessel:"OCEANIC STAR",imo:"9318474",port:"SGSIN",portName:"Singapore",stage:"outbound",activity:"Outbound",confidence:"94/100",confidenceLabel:"DEMO CONFIDENCE",source:"demo",events:[["All Fast","06:44","actual"],["Gangway Down","06:56","actual"],["Cargo Ops Started","07:31","actual"],["Cargo Ops Completed","17:22","actual"],["Ready to Sail","17:48","actual"],["Last Line","EST 18:20","current"],["Pilot Off","EST 18:46","estimated"],["Port Clear","EST 18:58","estimated"]]}
];
const roles=["VTS operator","Pilot","Tug crew","Mooring crew","Terminal operator","Ship agent","Master / Bridge","Port professional"];
const anchorageEvents=["Anchor Dropped","Anchor Aweigh"];
const events=["Pilot on Board","Tugs Connected","First Line","All Fast","Gangway Down","Cargo Operations Started","Cargo Operations Completed","Vessel Ready to Sail","Last Line","Pilot Off","Port Clear"];const shiftingEvents=["Shifting Started","Shifting Completed"];const reportEvents=[...events.slice(0,8),...shiftingEvents,...events.slice(8)];
function MooringBollard(){return <svg className="bollardIcon" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M7 6.5h10M8.5 6.5l1.2 11h4.6l1.2-11M7.7 17.5h8.6M5 10.5c2.2 0 3.4.8 4.4 2.1M19 10.5c-2.2 0-3.4.8-4.4 2.1"/></svg>}
async function fetchLiveReports():Promise<LiveReport[]>{const response=await fetch("/api/reports",{cache:"no-store"});if(!response.ok)return[];const body=await response.json() as {reports?:LiveReport[]};return body.reports??[]}
function stageFor(reports:LiveReport[]):PortCall["stage"]{const actual=[...reports].filter(x=>x.timeBasis==="actual").sort((a,b)=>a.eventTimeUtc.localeCompare(b.eventTimeUtc));const latest=actual.at(-1)?.eventType;if(latest==="Shifting Started")return"shifting";if(latest==="Shifting Completed")return"alongside";if(latest&&["Last Line","Pilot Off","Port Clear","Vessel Ready to Sail"].includes(latest))return"outbound";if(actual.some(x=>["All Fast","Gangway Down","Cargo Operations Started","Cargo Operations Completed"].includes(x.eventType)))return"alongside";if(actual.some(x=>["Pilot on Board","Tugs Connected","First Line","Anchor Aweigh"].includes(x.eventType)))return"inbound";if(actual.some(x=>x.eventType==="Anchor Dropped"))return"anchorage";return"inbound"}
function demoCallsForDisplay(displayTime:"port_local"|"utc"){if(displayTime==="utc")return demoCalls;const day=new Date().toISOString().slice(0,10);return demoCalls.map(call=>{const timezone=portTimezones[call.port]?.timezone;if(!timezone)return call;const convert=(value:string)=>value.replace(/(EST )?(\d{2}:\d{2})/,(_,est,time)=>`${est??""}${shortTime(utcToPortTime(`${day}T${time}`,timezone))}`);return{...call,anchorage:call.anchorage?{...call.anchorage,detail:`${convert(call.anchorage.detail.replace(" UTC",""))} PORT LOCAL`}:undefined,events:call.events.map(([name,time,state,meta])=>[name,convert(time),state,meta] as [string,string,EventState,string?])}})}
function liveCallsFrom(reports:LiveReport[],displayTime:"port_local"|"utc"):PortCall[]{
 const groups=new Map<string,LiveReport[]>();
 for(const report of reports)groups.set(report.portCallId,[...(groups.get(report.portCallId)??[]),report]);
 return[...groups.entries()].map(([id,group])=>{
  const sorted=[...group].sort((a,b)=>a.eventTimeUtc.localeCompare(b.eventTimeUtc));const selected=new Map<string,LiveReport>();
  for(const row of sorted){const existing=selected.get(row.eventType);if(!existing||(row.timeBasis==="actual"&&existing.timeBasis!=="actual")||(row.timeBasis==="planned"&&existing.timeBasis==="estimated")||(row.status==="verified"&&existing.status!=="verified"))selected.set(row.eventType,row)}
  const reported=[...selected.values()];const allVerified=reported.every(x=>x.status==="verified");const stage=stageFor(reported);const display=(x:LiveReport)=>displayTime==="port_local"&&x.portTimezone?shortTime(utcToPortTime(x.eventTimeUtc,x.portTimezone)):shortTime(x.eventTimeUtc);const reference=displayTime==="port_local"&&reported.some(x=>x.portTimezone)?"PORT LOCAL":"UTC";const dropped=selected.get("Anchor Dropped");const aweigh=selected.get("Anchor Aweigh");const anchorageReports=[dropped,aweigh].filter((x):x is LiveReport=>Boolean(x));let anchorage:AnchorageContext|undefined;
  if(anchorageReports.length){const status=anchorageReports.every(x=>x.status==="verified")?"VERIFIED":"REPORTED";if(dropped&&aweigh){const duration=Math.max(0,Date.parse(`${aweigh.eventTimeUtc}Z`)-Date.parse(`${dropped.eventTimeUtc}Z`));const hours=Math.floor(duration/3600000);const minutes=Math.floor((duration%3600000)/60000);anchorage={label:"ANCHORAGE",detail:`${hours} h ${String(minutes).padStart(2,"0")} min · ${display(dropped)}–${display(aweigh)} ${reference}`,status}}else if(dropped)anchorage={label:"AT ANCHORAGE",detail:`Since ${display(dropped)} ${reference}`,status};else if(aweigh)anchorage={label:"ANCHORAGE DEPARTURE",detail:`${display(aweigh)} ${reference}`,status}}
  const timelineEvents=selected.has("Shifting Started")||selected.has("Shifting Completed")?reportEvents:events;
  const timeline=timelineEvents.map(name=>{const x=selected.get(name);if(!x)return[name,"—","pending","Awaiting report"] as [string,string,EventState,string];const sourceMeta=x.independentSources>1?` · ${x.independentSources} independent sources · ${x.timeSpreadMinutes} min range`:"";const shown=display(x);if(x.timeBasis==="estimated")return[name,`EST ${shown}`,"estimated",`${x.status==="verified"?"Verified":"Reported"} estimate${sourceMeta}`,x.ownReportId??x.id,x.eventTimeUtc,Boolean(x.ownReportId),x.status==="verified"] as [string,string,EventState,string,number,string,boolean,boolean];if(x.timeBasis==="planned")return[name,`PLN ${shown}`,"planned",`${x.status==="verified"?"Verified":"Reported"} planned time${sourceMeta}`,x.ownReportId??x.id,x.eventTimeUtc,Boolean(x.ownReportId),x.status==="verified"] as [string,string,EventState,string,number,string,boolean,boolean];return[name,shown,x.status==="verified"?"actual":"reported",`${x.status==="verified"?"Verified actual":"Reported · Pending verification"}${sourceMeta}`,x.ownReportId??x.id,x.eventTimeUtc,Boolean(x.ownReportId),x.status==="verified"] as [string,string,EventState,string,number,string,boolean,boolean]});
  const known=portTimezones[sorted[0].portCode];const location=[...reported].reverse().find(x=>x.berth||x.terminal||x.pilotBoardingPlace);const locationContext=[location?.terminal,location?.berth,location?.pilotBoardingPlace].filter(Boolean).join(" · ");
  return{id,vessel:sorted[0].vesselName,imo:sorted[0].imo,port:sorted[0].portCode,portName:known?.name??sorted[0].portCode,timezone:sorted[0].portTimezone,locationContext,stage,activity:stage==="anchorage"?"At anchorage":stage==="alongside"?"Alongside":stage==="shifting"?"Shifting":stage==="outbound"?"Outbound":"Inbound",confidence:allVerified?"VERIFIED":"REPORTED",confidenceLabel:"LIVE DATA STATUS",source:"live",anchorage,events:timeline}
 })
}

export function VHF14Home({initialReportOpen=false}:{initialReportOpen?:boolean}){
 const[query,setQuery]=useState("");const[portQuery,setPortQuery]=useState("");const[selectedFilterPort,setSelectedFilterPort]=useState<PortOption|null>(null);const[filterPortOptions,setFilterPortOptions]=useState<PortOption[]>([]);const[stage,setStage]=useState("all");const[open,setOpen]=useState(initialReportOpen);const[notice,setNotice]=useState("");const[submittedId,setSubmittedId]=useState<number|null>(null);const[liveReports,setLiveReports]=useState<LiveReport[]>([]);const[page,setPage]=useState(1);const[pageSize,setPageSize]=useState(10);const[authenticated,setAuthenticated]=useState<boolean|null>(null);const[displayTime,setDisplayTime]=useState<"port_local"|"utc">(()=>typeof window!=="undefined"&&localStorage.getItem("vhf14-time-display")==="utc"?"utc":"port_local");const[portSearch,setPortSearch]=useState("");const[selectedPort,setSelectedPort]=useState<PortOption|null>(null);const[portOptions,setPortOptions]=useState<PortOption[]>([]);const[timeReference,setTimeReference]=useState<"port_local"|"utc">("port_local");const[eventTime,setEventTime]=useState("");
 const[quickTarget,setQuickTarget]=useState<QuickTarget|null>(null);const[quickBasis,setQuickBasis]=useState<"actual"|"estimated"|"planned">("actual");const[quickTime,setQuickTime]=useState("");const[quickReference,setQuickReference]=useState<"port_local"|"utc">("utc");const[quickEditing,setQuickEditing]=useState(false);const[quickReason,setQuickReason]=useState("");const[quickNotice,setQuickNotice]=useState("");const[quickSubmitting,setQuickSubmitting]=useState(false);
 useEffect(()=>{let active=true;const refresh=()=>fetchLiveReports().then(rows=>{if(active)setLiveReports(rows)});void refresh();const timer=setInterval(refresh,30000);return()=>{active=false;clearInterval(timer)}},[]);
 useEffect(()=>{fetch("/api/account",{cache:"no-store"}).then(r=>setAuthenticated(r.ok)).catch(()=>setAuthenticated(false))},[]);
 // prepareQuick intentionally reads the current display preference when authentication completes.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(authenticated!==true)return;const saved=sessionStorage.getItem("vhf14-quick-target");if(!saved)return;sessionStorage.removeItem("vhf14-quick-target");try{const target=JSON.parse(saved) as QuickTarget;prepareQuick(target)}catch{}},[authenticated]);
 useEffect(()=>{if(portSearch.trim().length<2||selectedPort&&portSearch===`${selectedPort.name} · ${selectedPort.code}`)return;const controller=new AbortController();const timer=setTimeout(()=>fetch(`/api/ports?q=${encodeURIComponent(portSearch)}`,{signal:controller.signal}).then(r=>r.json()).then((body:{ports?:PortOption[]})=>setPortOptions(body.ports??[])).catch(()=>{}),180);return()=>{clearTimeout(timer);controller.abort()}},[portSearch,selectedPort]);
 useEffect(()=>{if(portQuery.trim().length<2||selectedFilterPort&&portQuery===`${selectedFilterPort.name} · ${selectedFilterPort.code}`)return;const controller=new AbortController();const timer=setTimeout(()=>fetch(`/api/ports?q=${encodeURIComponent(portQuery)}`,{signal:controller.signal}).then(r=>r.json()).then((body:{ports?:PortOption[]})=>setFilterPortOptions(body.ports??[])).catch(()=>{}),180);return()=>{clearTimeout(timer);controller.abort()}},[portQuery,selectedFilterPort]);
 const selectedTimezone=selectedPort?.timezone??"";const convertedUtc=eventTime?(timeReference==="utc"?eventTime:localTimeToUtc(eventTime,selectedTimezone)):null;
 const allCalls=useMemo(()=>[...liveCallsFrom(liveReports,displayTime),...demoCallsForDisplay(displayTime)],[liveReports,displayTime]);const shown=useMemo(()=>allCalls.filter(c=>(!query||`${c.vessel} ${c.imo}`.toLowerCase().includes(query.toLowerCase()))&&(selectedFilterPort?c.port===selectedFilterPort.code:!portQuery||`${c.port} ${c.portName}`.toLowerCase().includes(portQuery.toLowerCase()))&&(stage==="all"||c.stage===stage)),[allCalls,query,portQuery,selectedFilterPort,stage]);
 const pageCount=Math.max(1,Math.ceil(shown.length/pageSize));const currentPage=Math.min(page,pageCount);const paged=shown.slice((currentPage-1)*pageSize,currentPage*pageSize);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedPort){setNotice("Select a port from the official results.");return}if(timeReference==="port_local"&&!selectedTimezone){setNotice("Port Local Time is unavailable for this location. Select UTC.");return}if(!convertedUtc){setNotice("Check the event time.");return}setNotice("Submitting…");setSubmittedId(null);const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));const payload={...values,portCode:selectedPort.code,eventTimeOriginal:eventTime,eventTimeUtc:convertedUtc,timeReference,portTimezone:selectedTimezone};const r=await fetch("/api/reports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const b=await r.json() as {error?:string;report?:{id:number}};if(!r.ok||!b.report){setNotice(b.error||"Unable to submit report");return}setNotice(`Report #${b.report.id} is live · Pending verification.`);setSubmittedId(b.report.id);form.reset();setEventTime("");setPortSearch("");setSelectedPort(null);setPortOptions([]);setTimeReference("port_local");setLiveReports(await fetchLiveReports())}
 function prepareQuick(target:QuickTarget){const reference=target.timezone&&displayTime==="port_local"?"port_local":"utc";const base=target.eventTimeUtc??new Date().toISOString().slice(0,16);setQuickTarget(target);setQuickReference(reference);setQuickTime(reference==="port_local"&&target.timezone?utcToPortTime(base,target.timezone):base);setQuickEditing(Boolean(target.verified));setQuickBasis(target.state==="estimated"?"estimated":target.state==="planned"?"planned":"actual");setQuickReason("");setQuickNotice("")}
 function openQuick(call:PortCall,eventName:string,state:EventState,reportId?:number,eventTimeUtc?:string,isOwn?:boolean,verified?:boolean){if(call.source!=="live")return;const target:QuickTarget={reportId,vessel:call.vessel,imo:call.imo,port:call.port,portName:call.portName,timezone:call.timezone??"",eventName,state,eventTimeUtc,isOwn,verified};if(authenticated!==true){sessionStorage.setItem("vhf14-quick-target",JSON.stringify(target));window.location.href="/signin?return_to=%2F";return}prepareQuick(target)}
 async function submitQuick(){
  if(!quickTarget)return;const utc=quickReference==="utc"?quickTime:localTimeToUtc(quickTime,quickTarget.timezone);if(!utc){setQuickNotice("Check the event time.");return}setQuickSubmitting(true);setQuickNotice("Submitting…");
  if(quickTarget.verified){const r=await fetch("/api/corrections",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reportId:quickTarget.reportId,eventTimeUtc:utc,reason:quickReason})});const b=await r.json() as {error?:string};setQuickNotice(r.ok?"Correction sent for review. The verified time remains visible until approval.":b.error??"Unable to send correction");setQuickSubmitting(false);return}
  if(quickTarget.isOwn&&quickTarget.reportId){const r=await fetch("/api/my-reports",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"quick_edit",id:quickTarget.reportId,eventTimeUtc:utc,eventTimeOriginal:quickTime,timeReference:quickReference,timeBasis:quickBasis})});const b=await r.json() as {error?:string};if(r.ok){setQuickNotice("Your report has been updated and remains pending verification.");setLiveReports(await fetchLiveReports())}else setQuickNotice(b.error??"Unable to update report");setQuickSubmitting(false);return}
  const payload={vesselName:quickTarget.vessel,imo:quickTarget.imo,portCode:quickTarget.port,eventType:quickTarget.eventName,eventTimeOriginal:quickTime,eventTimeUtc:utc,timeReference:quickReference,portTimezone:quickTarget.timezone,timeBasis:quickBasis,sourceRole:"Port professional",reportingCapacity:"personal",organisation:"",terminal:"",berth:"",pilotBoardingPlace:"",notes:"Quick timeline report",acceptedPolicy:"on"};const r=await fetch("/api/reports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const b=await r.json() as {error?:string};
  if(r.ok){setQuickNotice(quickBasis==="estimated"?"Estimate published and clearly marked EST.":quickBasis==="planned"?"Planned time published and clearly marked PLN.":"Actual time reported. It is visible now and pending verification.");setLiveReports(await fetchLiveReports())}else setQuickNotice(b.error??"Unable to submit report");setQuickSubmitting(false)
 }
 function clear(){setQuery("");setPortQuery("");setSelectedFilterPort(null);setFilterPortOptions([]);setStage("all");setPage(1)}function openReport(){if(authenticated===false){window.location.href="/signin?return_to=%2Freport";return}setOpen(true)}
 return <main>
  <header className="top"><a className="brand" href="/"><b>14</b><span>VHF14<small>PORT OPERATIONS INTELLIGENCE</small></span></a><span className="betaBadge">FREE BETA</span><nav><a href="/#feed">Operations</a><a href="/pricing">Free Beta</a><a href="/contact">Contact</a><a href={authenticated===false?"/signin?return_to=%2Faccount":"/account"}>{authenticated===false?"Sign in":"My account"}</a><button type="button" onClick={openReport}>Report event +</button></nav></header>
  <section className="betaNotice"><b>Live contribution feed</b><span>Professional reports appear immediately as Reported. Verified is granted only by authorised review; source agreement remains a separate confidence signal.</span><a href="/pricing#reciprocity">How credits work</a></section>
  <section className="hero"><div><p className="kicker">PROFESSIONAL · STRUCTURED · TRACEABLE</p><h1>PORT CALL DATA.<em>PEOPLE MAKING PORTS WORK.</em></h1><p>Operational reports from VTS, pilots, tug crews, mooring teams, terminals, agents and ships—structured into clear timelines with traceable confidence.</p></div><label className="search"><span>FIND A VESSEL</span><span className="searchField"><Search aria-hidden="true"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Vessel name or IMO number…"/></span><small>Search identifies a vessel. Port and stage filters refine the feed.</small></label></section>
  <section className="portCommunity" aria-label="Join VHF14 by professional role"><a href="/join/vts"><TowerControl/><span>VTS</span></a><a href="/join/pilot"><Anchor/><span>Pilots</span></a><a href="/join/tug"><Ship/><span>Tug Operators</span></a><a href="/join/mooring"><MooringBollard/><span>Mooring Teams</span></a><a href="/join/terminal"><Boxes/><span>Terminals</span></a><a href="/join/agent"><FileText/><span>Port Agents</span></a><a href="/join/crew"><Users/><span>Ship Crews</span></a></section>
  <section className="feed" id="feed"><div className="feedHead"><div><p className="kicker">LIVE + DEMONSTRATION DATA</p><h2>Port-call timelines</h2><p className="demoWarning">Live reports are consolidated into a consensus time when independent observations fall within the operational tolerance. Demonstration calls remain clearly labelled.</p></div><fieldset className="timeDisplay"><legend>DISPLAY TIMES</legend><button type="button" className={displayTime==="port_local"?"active":""} onClick={()=>{setDisplayTime("port_local");localStorage.setItem("vhf14-time-display","port_local")}}>Port Local Time</button><button type="button" className={displayTime==="utc"?"active":""} onClick={()=>{setDisplayTime("utc");localStorage.setItem("vhf14-time-display","utc")}}>UTC</button></fieldset></div>
   <div className="filters"><label className="filterPortPicker">PORT<input type="search" name="vhf14-port-filter" role="combobox" aria-expanded={filterPortOptions.length>0} aria-controls="filter-port-results" aria-autocomplete="list" autoComplete="off" autoCorrect="off" spellCheck={false} value={portQuery} onChange={e=>{setPortQuery(e.target.value);setSelectedFilterPort(null);if(e.target.value.trim().length<2)setFilterPortOptions([])}} placeholder="Port name or UN/LOCODE…"/>{filterPortOptions.length>0&&<ul id="filter-port-results" role="listbox">{filterPortOptions.map(port=><li key={port.code}><button type="button" onClick={()=>{setSelectedFilterPort(port);setPortQuery(`${port.name} · ${port.code}`);setFilterPortOptions([]);setPage(1)}}><b>{port.name}</b><span>{port.countryName}{port.subdivision?` · ${port.subdivision}`:""}</span><strong>{port.code}</strong></button></li>)}</ul>}</label><fieldset><legend>VESSEL STAGE</legend>{["all","anchorage","inbound","alongside","shifting","outbound"].map(x=><button type="button" key={x} className={stage===x?"active":""} onClick={()=>setStage(x)}>{x==="all"?"All active":x==="anchorage"?"At anchorage":x}</button>)}</fieldset><button type="button" className="clear" onClick={clear}>Clear filters</button></div>
   <div className="resultsBar"><p className="summary">Showing {shown.length?`${(currentPage-1)*pageSize+1}–${Math.min(currentPage*pageSize,shown.length)} of `:""}{shown.length} port {shown.length===1?"call":"calls"} · {shown.filter(x=>x.source==="live").length} live</p><label>SHOW<select value={pageSize} onChange={e=>setPageSize(Number(e.target.value))}>{[5,10,15,20].map(n=><option key={n}>{n}</option>)}</select></label></div>
   <div className="calls">{paged.map(c=><article className="call" key={c.id}>
    <div className="callHead"><div><span className={`stage ${c.stage}`}>{c.activity}</span><span className={`sourceTag ${c.source}`}>{c.source==="live"?"LIVE REPORT":"DEMO"}</span><h3>{c.vessel}</h3><p>IMO {c.imo} · {c.portName}{c.portName!==c.port&&` · ${c.port}`}{c.locationContext&&<> · {c.locationContext}</>}</p></div><div className="score"><span>{c.confidenceLabel}</span><b>{c.confidence}</b></div></div>
    {c.anchorage&&<aside className="anchorageContext"><Anchor aria-hidden="true"/><div><b>{c.anchorage.label}</b><span>{c.anchorage.detail}</span></div><small className={`anchorageStatus ${c.anchorage.status.toLowerCase()}`}>{c.anchorage.status}</small></aside>}
    <span className="swipeHint">Scroll / swipe timeline ↔</span><div className="timeline">{c.events.map(([name,time,state,meta,reportId,eventTimeUtc,isOwn,verified],i)=>{const content=<><i>{verified||c.source==="demo"&&state==="actual"?"✓":""}</i><b>{name}</b><time>{time}</time><small>{meta??(state==="reported"?"pending verification":state)}</small>{c.source==="live"&&<span className="quickHint">{verified?"View or correct":isOwn?"Edit my report":state==="reported"?"Add observation":state==="estimated"?"Review estimate":state==="planned"?"Review planned time":"Report now"}</span>}</>;return c.source==="live"?<button type="button" className={`event ${state} interactive`} key={`${name}-${i}`} onClick={()=>openQuick(c,name,state,reportId,eventTimeUtc,isOwn,verified)}>{content}</button>:<div className={`event ${state}`} key={`${name}-${i}`}>{content}</div>})}</div>
   </article>)}</div>
   {!shown.length&&<div className="empty">No port calls match this view.<button type="button" onClick={clear}>Show all calls</button></div>}{shown.length>pageSize&&<nav className="pagination" aria-label="Port call pages"><button disabled={currentPage===1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><span>Page {currentPage} of {pageCount}</span><button disabled={currentPage===pageCount} onClick={()=>setPage(p=>Math.min(pageCount,p+1))}>Next</button></nav>}
  </section>
  <footer><span className="footerIdentity"><b>VHF14 · PORT OPERATIONS INTELLIGENCE</b><small>Operated by Maritime Intelligence S.L.U. · © 2026</small></span><nav><a href="/data-dictionary">Data dictionary</a><a href="/contact">Contact</a><a href="/legal/notice">Legal Notice</a><a href="/legal/terms">Terms</a><a href="/legal/privacy">Privacy</a><a href="/legal/data">Data & verification</a></nav></footer>
  {open&&<div className="modal reportModal" role="dialog" aria-modal="true" aria-labelledby="report-title"><form className="reportForm" onSubmit={submit}>
   <div className="modalHead"><div><p className="kicker">STRUCTURED REPORT</p><h2 id="report-title">Report an operational event</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close">×</button></div>
   <p>Enter the operational time. VHF14 converts Port Local Time to UTC automatically.</p>
   <div className="reportCore"><label>VESSEL NAME<input name="vesselName" required minLength={2}/></label><label>IMO NUMBER<input name="imo" required inputMode="numeric" pattern="(?:IMO\s*)?\d{7}" placeholder="7 digits"/></label>
   <label className="portPicker">PORT<input role="combobox" aria-expanded={portOptions.length>0} aria-controls="port-results" aria-autocomplete="list" autoComplete="off" required placeholder="Search by port name or UN/LOCODE…" value={portSearch} onChange={e=>{setPortSearch(e.target.value);setSelectedPort(null);if(e.target.value.trim().length<2)setPortOptions([])}}/>{portOptions.length>0&&<ul id="port-results" role="listbox">{portOptions.map(port=><li key={port.code}><button type="button" onClick={()=>{setSelectedPort(port);setPortSearch(`${port.name} · ${port.code}`);setPortOptions([]);if(!port.timezone)setTimeReference("utc")}}><b>{port.name}</b><span>{port.countryName}{port.subdivision?` · ${port.subdivision}`:""}</span><strong>{port.code}</strong></button></li>)}</ul>}{selectedPort&&<small className="selectedPort">{selectedPort.name}, {selectedPort.countryName} · {selectedPort.code}{selectedPort.timezone?` · ${selectedPort.timezone}`:" · UTC only"}</small>}<small className="fieldHint">Official UN/LOCODE port directory · search by name or five-character code.</small></label>
   <label>EVENT<select name="eventType" defaultValue="Pilot on Board"><optgroup label="Port-call timeline">{reportEvents.map(x=><option key={x}>{x}</option>)}</optgroup><optgroup label="Anchorage context">{anchorageEvents.map(x=><option key={x}>{x}</option>)}</optgroup></select><small className="fieldHint">Anchorage reports appear as optional context and do not add steps to the main timeline.</small></label></div>
   <fieldset className="timeReference"><legend>TIME REFERENCE</legend><label><input type="radio" name="timeReferenceChoice" checked={timeReference==="port_local"} disabled={Boolean(selectedPort&&!selectedTimezone)} onChange={()=>setTimeReference("port_local")}/> Port Local Time</label><label><input type="radio" name="timeReferenceChoice" checked={timeReference==="utc"} onChange={()=>setTimeReference("utc")}/> UTC</label></fieldset>{selectedPort&&!selectedTimezone&&<small className="timeUnavailable">This location has no confirmed timezone in the source data. Enter the event in UTC.</small>}
   <div className="two"><label>EVENT DATE AND TIME<input type="datetime-local" required value={eventTime} onChange={e=>setEventTime(e.target.value)}/>{convertedUtc&&<small className="timeConversion">{timeReference==="port_local"?`${eventTime.replace("T"," ")} Port Local Time = ${convertedUtc.replace("T"," ")} UTC (${timezoneOffsetLabel(convertedUtc,selectedTimezone)})`:`${convertedUtc.replace("T"," ")} UTC`}</small>}</label><label>TIME TYPE<select name="timeBasis" defaultValue="actual"><option value="actual">Actual · observed</option><option value="estimated">Estimated · expected</option><option value="planned">Planned · current operational plan</option></select></label></div>
   <fieldset className="optionalContext"><legend>OPTIONAL OPERATIONAL LOCATION</legend><div className="three"><label>TERMINAL<input name="terminal" maxLength={120}/></label><label>BERTH<input name="berth" maxLength={120}/></label><label>PILOT BOARDING PLACE<input name="pilotBoardingPlace" maxLength={160}/></label></div><small>Leave blank when unknown. Do not enter confidential or security-sensitive information.</small></fieldset>
   <div className="two"><label>PROFESSIONAL ROLE<select name="sourceRole">{roles.map(x=><option key={x}>{x}</option>)}</select></label><label>REPORTING CAPACITY<select name="reportingCapacity"><option value="personal">Personal professional capacity</option><option value="organisation">On behalf of my organisation</option></select></label></div><label>ORGANISATION (OPTIONAL)<input name="organisation" maxLength={150}/></label><label>NOTES<textarea name="notes" maxLength={1000}/></label><label className="consent"><input type="checkbox" name="acceptedPolicy" required/> I confirm this is a good-faith professional report, that I am authorised to share it, and accept the <a href="/legal/data" target="_blank">Data & Verification Policy</a>.</label><button className="submit">Publish report</button><output>{notice}{submittedId&&<> <a className="editNow" href="/account#my-reports">Edit this report</a></>}</output>
  </form></div>}
  {quickTarget&&<div className="modal quickModal" role="dialog" aria-modal="true" aria-labelledby="quick-title"><section className="quickCard">
   <div className="modalHead"><div><p className="kicker">{quickTarget.verified?"VERIFIED EVENT":quickTarget.isOwn?"EDIT MY REPORT":"QUICK REPORT"}</p><h2 id="quick-title">{quickTarget.eventName}</h2></div><button type="button" onClick={()=>setQuickTarget(null)} aria-label="Close">×</button></div>
   <p><b>{quickTarget.vessel}</b> · {quickTarget.portName} · {quickTarget.port}</p>{quickTarget.verified?<p>The verified value stays unchanged while a correction is reviewed. If approved, VHF14 publishes a new version and retains the complete history.</p>:quickTarget.isOwn?<p>Update your pending time directly. The previous value remains in the audit history.</p>:<><p>Confirm the event now, or enter an actual, estimated or planned time.</p>{!quickEditing&&<p className="quickClock">{quickTime.replace("T"," ")} {quickReference==="port_local"?"Port Local Time":"UTC"}</p>}</>}
   <fieldset className="timeReference"><legend>TIME REFERENCE</legend><label><input type="radio" checked={quickReference==="port_local"} disabled={!quickTarget.timezone} onChange={()=>{setQuickReference("port_local");const utc=quickReference==="utc"?quickTime:localTimeToUtc(quickTime,quickTarget.timezone);if(utc)setQuickTime(utcToPortTime(utc,quickTarget.timezone))}}/> Port Local Time</label><label><input type="radio" checked={quickReference==="utc"} onChange={()=>{const utc=quickReference==="utc"?quickTime:localTimeToUtc(quickTime,quickTarget.timezone);setQuickReference("utc");if(utc)setQuickTime(utc)}}/> UTC</label></fieldset>
   {(quickEditing||quickTarget.verified||quickTarget.isOwn)&&<label>{quickBasis==="estimated"?"ESTIMATED DATE AND TIME":quickBasis==="planned"?"PLANNED DATE AND TIME":"ACTUAL DATE AND TIME"}<input type="datetime-local" value={quickTime} onChange={e=>setQuickTime(e.target.value)}/>{quickTime&&<small className="timeConversion">{quickReference==="port_local"?`${quickTime.replace("T"," ")} Port Local Time = ${localTimeToUtc(quickTime,quickTarget.timezone)?.replace("T"," ")??"—"} UTC`:`${quickTime.replace("T"," ")} UTC`}</small>}</label>}
   {quickTarget.isOwn&&!quickTarget.verified&&<label>TIME TYPE<select value={quickBasis} onChange={e=>setQuickBasis(e.target.value as "actual"|"estimated"|"planned")}><option value="actual">Actual · observed</option><option value="estimated">Estimated · expected</option><option value="planned">Planned · current operational plan</option></select></label>}
   {quickTarget.verified&&<label>REASON FOR CORRECTION<textarea required minLength={5} maxLength={500} value={quickReason} onChange={e=>setQuickReason(e.target.value)} placeholder="Briefly explain what should change and why."/></label>}
   <div className="quickActions">{!quickTarget.verified&&!quickEditing&&!quickTarget.isOwn&&<button type="button" className="submit" disabled={quickSubmitting} onClick={submitQuick}>Report actual now</button>}{!quickTarget.verified&&!quickEditing&&!quickTarget.isOwn&&<button type="button" onClick={()=>{setQuickBasis("actual");setQuickEditing(true)}}>Enter actual time</button>}{!quickTarget.verified&&!quickEditing&&!quickTarget.isOwn&&<button type="button" onClick={()=>{setQuickBasis("estimated");setQuickEditing(true)}}>Add estimated time</button>}{!quickTarget.verified&&!quickEditing&&!quickTarget.isOwn&&<button type="button" onClick={()=>{setQuickBasis("planned");setQuickEditing(true)}}>Add planned time</button>}{(quickEditing||quickTarget.verified||quickTarget.isOwn)&&<button type="button" className="submit" disabled={quickSubmitting||Boolean(quickTarget.verified&&quickReason.trim().length<5)} onClick={submitQuick}>{quickTarget.verified?"Submit correction":quickTarget.isOwn?"Save changes":quickBasis==="estimated"?"Publish estimate":quickBasis==="planned"?"Publish planned time":"Submit actual time"}</button>}<button type="button" onClick={()=>setQuickTarget(null)}>Close</button></div><output>{quickNotice}</output>
  </section></div>}
 </main>
}
export default function Home(){return <VHF14Home/>}
