import { eq } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "../../../db";
import { professionalProfiles } from "../../../db/schema";
import { getChatGPTUser } from "../../chatgpt-auth";

const schema=z.object({professionalRole:z.enum(["vts","pilot","tug","mooring","terminal","agent","crew"]),fullName:z.string().trim().min(2).max(100),jobTitle:z.string().trim().min(2).max(100),participationType:z.enum(["individual","organisation"]),organisation:z.string().trim().max(150).default(""),organisationType:z.string().trim().max(100).default(""),organisationWebsite:z.union([z.literal(""),z.string().url().max(200)]).default(""),corporateEmail:z.union([z.literal(""),z.string().email().max(150)]).default(""),legalRegistrationId:z.string().trim().max(100).default(""),authorityToRepresent:z.string().trim().max(300).default(""),portScope:z.string().trim().min(2).max(150),country:z.string().trim().min(2).max(80),professionalIdentifier:z.string().trim().max(100).default(""),verificationNotes:z.string().trim().max(1000).default(""),acceptedPolicy:z.literal("on")}).superRefine((data,ctx)=>{if(data.participationType==="organisation"){if(data.organisation.length<2)ctx.addIssue({code:"custom",path:["organisation"],message:"Organisation name is required"});if(!data.organisationType)ctx.addIssue({code:"custom",path:["organisationType"],message:"Organisation type is required"});if(!data.corporateEmail)ctx.addIssue({code:"custom",path:["corporateEmail"],message:"Corporate email is required"});if(data.authorityToRepresent.length<2)ctx.addIssue({code:"custom",path:["authorityToRepresent"],message:"Authority to represent is required"})}});
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:"Authentication required"},{status:401});const[profile]=await getDb().select().from(professionalProfiles).where(eq(professionalProfiles.userId,user.userId)).limit(1);return Response.json({profile:profile??null})}
export async function PUT(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:"Authentication required"},{status:401});const parsed=schema.safeParse(await request.json());if(!parsed.success)return Response.json({error:"Check the required profile fields",issues:parsed.error.flatten()},{status:400});const{acceptedPolicy:_,...data}=parsed.data;void _;const db=getDb();const[existing]=await db.select().from(professionalProfiles).where(eq(professionalProfiles.userId,user.userId)).limit(1);const values={...data,email:user.email,status:"pending" as const,organisationStatus:data.participationType==="organisation"?"pending" as const:"not_applicable" as const,professionalReviewedBy:null,professionalReviewedAt:null,organisationReviewedBy:null,organisationReviewedAt:null,updatedAt:new Date().toISOString()};const[profile]=existing?await db.update(professionalProfiles).set(values).where(eq(professionalProfiles.userId,user.userId)).returning():await db.insert(professionalProfiles).values({...values,userId:user.userId}).returning();return Response.json({profile})}
