import { desc } from "drizzle-orm";
import { NativeLink as Link } from "../../native-link";
import { getDb } from "../../../db";
import { accounts, contributionCredits, professionalProfiles, reports } from "../../../db/schema";
import { requireVHF14Admin } from "../../chatgpt-auth";

export const dynamic="force-dynamic";
export default async function UsersPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 await requireVHF14Admin("/admin/users");const params=await searchParams;const db=getDb();
 const [accountRows,profiles,reportRows,credits]=await Promise.all([db.select().from(accounts).orderBy(desc(accounts.createdAt)),db.select().from(professionalProfiles),db.select().from(reports),db.select().from(contributionCredits)]);
 const byUser=new Map(profiles.map(p=>[p.userId,p]));const q=String(params.q??"").trim().toLowerCase();const state=String(params.status??"");const type=String(params.type??"");
 const rows=accountRows.filter(account=>{const p=byUser.get(account.userId);const hay=[account.fullName,account.email,account.company,p?.organisation,p?.professionalRole,p?.country,p?.portScope].filter(Boolean).join(" ").toLowerCase();const effective=account.status==="suspended"?"suspended":p?.status??"pending";return(!q||hay.includes(q))&&(!state||effective===state)&&(!type||p?.participationType===type)});
 return <main className="admin"><header><Link href="/admin">← Verification console</Link><div><p className="kicker">ADMIN · USERS &amp; PROFILES</p><h1>Users &amp; Profiles</h1><p>Account, professional identity, organisation representation and reporting activity remain separate.</p></div></header><form className="adminFilters"><input name="q" defaultValue={q} placeholder="Name, email, organisation, role, country or port"/><select name="status" defaultValue={state}><option value="">All statuses</option><option value="pending">Pending</option><option value="verified">Verified</option><option value="rejected">Rejected</option><option value="suspended">Suspended</option></select><select name="type" defaultValue={type}><option value="">Individual &amp; Organisation</option><option value="individual">Individual</option><option value="organisation">Organisation</option></select><button>Filter</button><Link href="/admin/users">Clear</Link></form><div className="userDirectory">{rows.map(account=>{const p=byUser.get(account.userId);const userReports=reportRows.filter(r=>r.reporterUserId===account.userId);const userCredits=credits.filter(c=>c.userId===account.userId).reduce((sum,c)=>sum+c.amount,0);return <Link className="userRow" href={`/admin/users/${encodeURIComponent(account.userId)}`} key={account.userId}><div><b>{account.fullName||"Unnamed account"}</b><small>{account.email}</small></div><span className={`status ${account.status}`}>account · {account.status}</span><span>{p?`${p.professionalRole} · ${p.participationType}`:"No profile"}</span><span className={`status ${p?.status??"pending"}`}>profile · {p?.status??"not created"}</span><span>{userReports.length} reports · {userCredits} credits</span></Link>})}{!rows.length&&<p className="empty">No users match these filters.</p>}</div></main>
}
