import { desc, eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { getDb } from "../../../../db";
import { accounts, adminAuditLog, adminNotes, contributionCredits, professionalProfiles, reportCorrections, reports } from "../../../../db/schema";
import { requireVHF14Admin, safeReturnPath } from "../../../chatgpt-auth";
import { NativeLink as Link } from "../../../native-link";
import { UserActions } from "../../user-actions";

export const dynamic="force-dynamic";
export default async function UserDetail({params,searchParams}:{params:Promise<{userId:string}>;searchParams:Promise<{return_to?:string}>}){
 const {userId}=await params;const query=await searchParams;const requestedReturn=safeReturnPath(query.return_to??"/admin/users");const returnTo=requestedReturn==="/admin/users"||requestedReturn.startsWith("/admin/users?")?requestedReturn:"/admin/users";await requireVHF14Admin(`/admin/users/${encodeURIComponent(userId)}?return_to=${encodeURIComponent(returnTo)}`);const db=getDb();
 const [[account],[profile],reportRows,credits,notes,audit,corrections]=await Promise.all([
  db.select().from(accounts).where(eq(accounts.userId,userId)).limit(1),
  db.select().from(professionalProfiles).where(eq(professionalProfiles.userId,userId)).limit(1),
  db.select().from(reports).where(eq(reports.reporterUserId,userId)).orderBy(desc(reports.createdAt)).limit(100),
  db.select().from(contributionCredits).where(eq(contributionCredits.userId,userId)).orderBy(desc(contributionCredits.createdAt)),
  db.select().from(adminNotes).where(eq(adminNotes.userId,userId)).orderBy(desc(adminNotes.createdAt)).limit(50),
  db.select().from(adminAuditLog).where(eq(adminAuditLog.subjectId,userId)).orderBy(desc(adminAuditLog.createdAt)).limit(100),
  db.select().from(reportCorrections).where(eq(reportCorrections.requesterUserId,userId)).orderBy(desc(reportCorrections.createdAt)).limit(100)
 ]);if(!account)notFound();const creditTotal=credits.reduce((sum,item)=>sum+item.amount,0);const verified=reportRows.filter(item=>item.status==="verified").length;const rejected=reportRows.filter(item=>item.status==="rejected").length;const reviewed=verified+rejected;const acceptance=reviewed?Math.round(verified/reviewed*100):null;const ports=[...new Set(reportRows.map(item=>item.portCode))];const eventTypes=[...new Set(reportRows.map(item=>item.eventType))];const lastReport=reportRows[0];const alerts:string[]=[];if(!profile)alerts.push("Professional profile not created");else{if(profile.status!=="verified")alerts.push(`Professional profile ${profile.status}`);if(!profile.professionalIdentifier)alerts.push("Professional identifier not supplied");if(!profile.verificationNotes)alerts.push("No supporting verification information");if(profile.participationType==="organisation"&&profile.organisationStatus!=="verified")alerts.push(`Organisation representation ${profile.organisationStatus}`)}if(reviewed>=3&&rejected/reviewed>=.3)alerts.push("Elevated rejected-report rate");
 const activity=[...reportRows.map(item=>({date:item.createdAt,type:"report",status:item.status,title:`${item.vesselName} · ${item.eventType}`,detail:`${item.portCode} · ${item.eventTimeUtc.replace("T"," ")} UTC`})),...corrections.map(item=>({date:item.createdAt,type:"correction",status:item.status,title:`Correction request · Report #${item.reportId}`,detail:item.reason})),...notes.map(item=>({date:item.createdAt,type:"internal note",status:"",title:"Internal note",detail:item.note})),...audit.map(item=>({date:item.createdAt,type:"administration",status:item.action,title:`${item.action} · ${item.subjectType}`,detail:item.reason}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,150);
 return <main className="admin"><nav className="adminBreadcrumb" aria-label="Breadcrumb"><Link href="/admin">Admin</Link><span>›</span><Link href={returnTo}>Users &amp; Profiles</Link><span>›</span><b>{account.fullName||profile?.fullName||"User detail"}</b></nav><header><Link href={returnTo}>← Users &amp; Profiles</Link><div><p className="kicker">ADMIN · USER DETAIL</p><h1>{account.fullName||profile?.fullName||"Unnamed account"}</h1><p>{account.email} · created {account.createdAt}</p></div></header>
  {alerts.length>0&&<section className="profileAlerts"><b>Attention</b>{alerts.map(alert=><span key={alert}>{alert}</span>)}</section>}
  <section className="adminGrid profileAdminGrid"><article><h2>Account</h2><dl><dt>Status</dt><dd><span className={`status ${account.status}`}>{account.status}</span></dd><dt>Email</dt><dd>{account.email}</dd><dt>User ID</dt><dd>{account.userId}</dd><dt>Role</dt><dd>{account.role}</dd><dt>Company</dt><dd>{account.company||"—"}</dd><dt>Plan</dt><dd>{account.plan} · {account.subscriptionStatus}</dd><dt>Created</dt><dd>{account.createdAt}</dd>{account.statusReason&&<><dt>Status reason</dt><dd>{account.statusReason}</dd></>}</dl></article><article><h2>Professional accreditation</h2>{profile?<dl><dt>Status</dt><dd><span className={`status ${profile.status}`}>{profile.status}</span></dd><dt>Role</dt><dd>{profile.professionalRole} · {profile.jobTitle}</dd><dt>Scope</dt><dd>{profile.portScope} · {profile.country}</dd><dt>Identifier</dt><dd>{profile.professionalIdentifier||"—"}</dd><dt>Verification information</dt><dd>{profile.verificationNotes||"—"}</dd><dt>Reviewed</dt><dd>{profile.professionalReviewedAt||"—"}</dd><dt>Reviewed by</dt><dd>{profile.professionalReviewedBy||"—"}</dd></dl>:<p>No professional profile has been created.</p>}</article><article><h2>Organisation</h2>{profile?.participationType==="organisation"?<dl><dt>Status</dt><dd><span className={`status ${profile.organisationStatus}`}>{profile.organisationStatus}</span></dd><dt>Name</dt><dd>{profile.organisation||"—"}</dd><dt>Type</dt><dd>{profile.organisationType||"—"}</dd><dt>Website</dt><dd>{profile.organisationWebsite?<a href={profile.organisationWebsite} target="_blank" rel="noreferrer">{profile.organisationWebsite}</a>:"—"}</dd><dt>Corporate email</dt><dd>{profile.corporateEmail||"—"}</dd><dt>Registration</dt><dd>{profile.legalRegistrationId||"—"}</dd><dt>Authority</dt><dd>{profile.authorityToRepresent||"—"}</dd><dt>Reviewed</dt><dd>{profile.organisationReviewedAt||"—"}</dd><dt>Reviewed by</dt><dd>{profile.organisationReviewedBy||"—"}</dd></dl>:<p>This user participates in an individual professional capacity.</p>}</article><article><h2>Reliability summary</h2><dl><dt>Reports</dt><dd>{reportRows.length}</dd><dt>Pending</dt><dd>{reportRows.filter(item=>item.status==="pending").length}</dd><dt>Verified</dt><dd>{verified}</dd><dt>Rejected</dt><dd>{rejected}</dd><dt>Acceptance</dt><dd>{acceptance===null?"Not enough reviewed reports":`${acceptance}%`}</dd><dt>Corrections</dt><dd>{corrections.length}</dd><dt>Credits</dt><dd>{creditTotal}</dd><dt>Last report</dt><dd>{lastReport?.createdAt??"—"}</dd><dt>Ports</dt><dd>{ports.join(", ")||"—"}</dd><dt>Event types</dt><dd>{eventTypes.join(", ")||"—"}</dd></dl></article></section>
  <UserActions userId={userId} status={account.status} hasProfile={Boolean(profile)} profileStatus={profile?.status} organisationStatus={profile?.organisationStatus}/>
  <section className="adminHistory"><h2>Reports</h2>{reportRows.map(report=><article key={report.id}><span className={`status ${report.status}`}>{report.status}</span><p><b>{report.vesselName}</b> · IMO {report.imo} · {report.portCode} · {report.eventType}</p><small>{report.eventTimeUtc.replace("T"," ")} UTC · submitted {report.createdAt}</small>{report.notes&&<p>{report.notes}</p>}</article>)}{!reportRows.length&&<p className="empty">No reports submitted.</p>}</section>
  <section className="adminHistory"><h2>Unified activity</h2>{activity.map((item,index)=><article key={`${item.type}-${item.date}-${index}`}><span className={`status ${item.status}`}>{item.type}{item.status?` · ${item.status}`:""}</span><p><b>{item.title}</b></p><p>{item.detail}</p><small>{item.date}</small></article>)}{!activity.length&&<p className="empty">No account activity.</p>}</section>
 </main>
}
