import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Anchor, Boxes, FileText, Ship, TowerControl, Users } from "lucide-react";
/* eslint-disable @next/next/no-html-link-for-pages */
import { getChatGPTUser, vhf14SignInPath } from "../../chatgpt-auth";
import { ProfessionalProfileForm } from "./professional-profile-form";

export const dynamic="force-dynamic";

const roleContent={
 vts:{name:"VTS",heading:"Join VHF14 as VTS",title:"VTS Port Call Data and Vessel Movements",description:"VTS professionals can contribute authorised UTC observations for vessel movements, anchorage, arrivals and departures to structured VHF14 port-call timelines.",lead:"Structure vessel-movement observations across the port call.",body:"Vessel Traffic Services professionals observe arrivals, departures, anchorage movements and key transitions within controlled waters. VHF14 connects authorised UTC observations in one traceable sequence across the complete port call.",events:["Vessel arrivals and departures","Anchorage and inbound movements","Pilot boarding and port-clear milestones"]},
 pilot:{name:"Pilot",heading:"Join VHF14 as a Marine Pilot",title:"Marine Pilot Berthing and Port Call Data",description:"Marine pilots can contribute pilot boarding, tug assistance, berthing and departure milestones to structured, traceable VHF14 port-call timelines.",lead:"Connect pilotage, berthing and departure milestones.",body:"Marine pilots observe critical transitions between the vessel, port approach and berth. VHF14 structures authorised observations such as pilot on board, tug connected, first line, all fast, last line and pilot off so each time can be understood within its operational context.",events:["Pilot on board and pilot off","Berthing, shifting and unberthing sequences","Tug, first-line and all-fast coordination"]},
 tug:{name:"Tug Operator",heading:"Join VHF14 as a Tug Operator",title:"Harbour Tug Operations and Port Call Data",description:"Tug operators can contribute harbour towage, tug connection and vessel-assistance milestones to structured, traceable VHF14 port-call timelines.",lead:"Place tug assistance within the complete port-call sequence.",body:"Tug operators and crews have direct knowledge of harbour towage, escort and vessel-assistance activity. VHF14 connects authorised tug observations with pilotage, mooring and berth events in one structured operational sequence.",events:["Tug connected and assistance times","Berthing and departure support","Operational context around vessel movements"]},
 mooring:{name:"Mooring Team",heading:"Join VHF14 as a Mooring Professional",title:"Mooring Operations and Port Call Data",description:"Mooring professionals can contribute first line, all fast, last line and unmooring observations to structured, traceable VHF14 port-call timelines.",lead:"Record the line-handling milestones that define berth arrival and departure.",body:"Mooring teams observe when a vessel first connects with the berth, becomes secured alongside and begins departure. VHF14 places authorised first-line, all-fast and last-line observations alongside related pilotage, tug and terminal events in one consistent UTC timeline.",events:["First line ashore","All fast confirmation","Last line and unmooring sequence"]},
 terminal:{name:"Terminal",heading:"Join VHF14 as a Terminal Professional",title:"Terminal Operations and Cargo Milestones",description:"Terminal professionals can contribute berth, gangway, cargo-operation and vessel-readiness milestones to structured VHF14 port-call timelines.",lead:"Connect berth and cargo events to the vessel's complete port call.",body:"Terminal professionals observe the alongside phase from berth readiness to completion of cargo operations. VHF14 relates authorised gangway, cargo and sailing-readiness observations to arrival and departure events, providing a consistent operational sequence.",events:["Gangway and berth milestones","Cargo operations started and completed","Vessel ready to sail"]},
 agent:{name:"Port Agent",heading:"Join VHF14 as a Port Agent",title:"Port Agency Operations and Port Call Data",description:"Port agents can contribute arrival, berth, service and departure updates to structured, traceable VHF14 port-call timelines.",lead:"Bring coordinated arrival, berth and departure updates into one timeline.",body:"Port agents coordinate vessels, service providers, terminals and port stakeholders throughout a call. VHF14 provides a common structure for authorised estimated and actual UTC updates, with professional identity and organisational representation reviewed separately.",events:["Arrival and departure coordination","Berth and service milestones","Estimated and actual UTC updates"]},
 crew:{name:"Ship Crew",heading:"Join VHF14 as Ship Crew",title:"Ship Crew Port Call and Departure Data",description:"Masters, bridge teams and authorised ship personnel can contribute anchoring, gangway, cargo-readiness and departure observations to VHF14.",lead:"Connect shipboard observations with the wider port operation.",body:"Masters, bridge teams and authorised ship personnel observe key events from anchorage through departure. VHF14 structures these operational times and connects the shipboard view with the wider port-call sequence.",events:["Anchoring and anchor aweigh","Gangway and cargo milestones","Readiness and port-clear events"]},
} as const;
type Role=keyof typeof roleContent;

export async function generateMetadata({params}:{params:Promise<{role:string}>}):Promise<Metadata>{const{role}=await params;if(!(role in roleContent))return{};const item=roleContent[role as Role];return{title:item.title,description:item.description,alternates:{canonical:`/join/${role}`},openGraph:{title:`${item.title} | VHF14`,description:item.description,url:`https://vhf14.com/join/${role}`},twitter:{card:"summary",title:`${item.title} | VHF14`,description:item.description}}}

function RoleIcon({role}:{role:Role}){if(role==="vts")return <TowerControl aria-hidden="true"/>;if(role==="pilot")return <Anchor aria-hidden="true"/>;if(role==="tug")return <Ship aria-hidden="true"/>;if(role==="terminal")return <Boxes aria-hidden="true"/>;if(role==="agent")return <FileText aria-hidden="true"/>;if(role==="crew")return <Users aria-hidden="true"/>;return <svg className="joinBollard" viewBox="0 0 64 64" fill="none" aria-hidden="true"><path d="M17 16h30M21 16l4 31h14l4-31M18 47h28M10 28c8 0 13 3 17 9M54 28c-8 0-13 3-17 9"/></svg>}

export default async function JoinRole({params}:{params:Promise<{role:string}>}){const{role}=await params;if(!(role in roleContent))notFound();const item=roleContent[role as Role];const user=await getChatGPTUser();return <main className="commercial joinPage"><header className="simpleTop"><a className="brand" href="/"><b>14</b><span>VHF14<small>PORT OPERATIONS INTELLIGENCE</small></span></a><nav><a href="/">Operations</a><a href={user?"/account":vhf14SignInPath(`/join/${role}`)}>{user?"My account":"Sign in"}</a></nav></header><section className="joinHero"><div className="joinCopy"><p className="kicker">PROFESSIONAL NETWORK</p><h1>{item.heading}</h1><h2>{item.lead}</h2><p>{item.body}</p><h3 className="joinMilestoneTitle">Operational milestones</h3><ul>{item.events.map(event=><li key={event}>{event}</li>)}</ul><p className="joinAssurance">Professional verification and organisational representation are reviewed separately.</p></div><aside className={`joinVisual role-${role}`} aria-label={`${item.name} operational illustration`}><RoleIcon role={role as Role}/><span>{item.name.toUpperCase()}</span><small>STRUCTURED UTC EVENTS</small></aside></section><ProfessionalProfileForm role={role as Role} authenticated={Boolean(user)} email={user?.email??""} name={user?.displayName??""}/></main>}
