/* eslint-disable @next/next/no-html-link-for-pages */

export default function Beta(){
 return <main className="commercial">
  <header className="simpleTop"><a className="brand" href="/"><b>14</b><span>VHF14<small>PORT OPERATIONS INTELLIGENCE</small></span></a><nav><a href="/#feed">Operations</a><a href="/contact">Contact</a><a href="/account">My account</a></nav></header>
  <section className="pricingIntro"><p className="kicker">FOUNDING NETWORK · FREE BETA</p><h1>Operational clarity for every port call.</h1><p>VHF14 brings together the professionals directly involved in every port call: VTS, pilots, tug crews, mooring crews, terminals, ship agents, masters and bridge teams.</p></section>
  <div className="betaCards"><article><span>01</span><h2>Consult</h2><p>Follow clear, standardised port-call timelines as verified coverage grows.</p></article><article><span>02</span><h2>Contribute</h2><p>Add the operational events you know directly, in a personal or authorised organisational capacity.</p></article><article><span>03</span><h2>Improve together</h2><p>Help make turnaround information more useful, traceable and efficient for the whole port community.</p></article></div>
  <section className="reciprocity" id="reciprocity"><p className="kicker">VHF14 CONTRIBUTION CREDITS</p><h2>Verified value earns greater access.</h2><p className="reciprocityLead">A reciprocal network rewards useful, verified information—not the volume of submissions. The same rule applies to VTS, pilots, tug and mooring crews, terminals, agents and ship teams.</p><div className="creditFlow"><article><span>01 · REPORT</span><b>Add a direct operational event</b><p>Submit only information you are authorised to share.</p></article><article><span>02 · VERIFY</span><b>Independent review confirms value</b><p>Duplicates and reports that cannot be verified earn no credit.</p></article><article><span>03 · EARN</span><b>Build your access allowance</b><p>Each accepted event earns 1 credit for future consultation of third-party port calls.</p></article></div><aside><b>Free Beta:</b> all available information remains open until the network reaches meaningful coverage. Credits accumulate without expiring or being spent. Before limits are introduced, contributors will receive advance notice and keep their full balance.</aside></section>
  <section className="founderCta"><div><p className="kicker">FREE BETA ACCESS</p><h2>Contribute knowledge. Receive a better operational picture.</h2><p>Free throughout the beta. Every professional group participates under the same structured reporting, verification and confidentiality principles.</p></div><div><a className="primaryLink" href="/account">Join free</a><a href="/contact">Contact VHF14</a></div></section>
 </main>
}
