import { and, desc, eq, gte, notInArray, sql } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "../../../db";
import { contributionCredits, reports } from "../../../db/schema";
import { isValidTimezone, localTimeToUtc, portTimezones } from "../../../lib/port-time";
import portCatalog from "../../../data/ports.json";
import { getChatGPTUser, isVHF14Admin, sameOrigin } from "../../chatgpt-auth";

const catalogTimezones=new Map((portCatalog.ports as [string,string,string,string,string,string,number|null,number|null][]).map(row=>[row[0],row[5]]));

const reportSchema = z.object({ vesselName: z.string().trim().min(2).max(100), imo: z.string().trim().regex(/^(?:IMO\s*)?\d{7}$/i), portCode: z.string().trim().toUpperCase().regex(/^[A-Z]{2}[A-Z0-9]{3}$/), eventType: z.enum(["Anchor Dropped", "Anchor Aweigh", "Pilot on Board", "Tugs Connected", "First Line", "All Fast", "Gangway Down", "Cargo Operations Started", "Cargo Operations Completed", "Vessel Ready to Sail", "Shifting Started", "Shifting Completed", "Last Line", "Pilot Off", "Port Clear"]), eventTimeOriginal:z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/), eventTimeUtc: z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/), timeReference:z.enum(["port_local","utc"]),portTimezone:z.string().trim().max(80),timeBasis:z.enum(["actual","estimated","planned"]), sourceRole: z.enum(["VTS operator", "Port professional", "Pilot", "Master / Bridge", "Terminal operator", "Tug crew", "Mooring crew", "Ship agent"]), reportingCapacity: z.enum(["personal", "organisation"]), organisation: z.string().trim().max(150).default(""), terminal:z.string().trim().max(120).default(""), berth:z.string().trim().max(120).default(""), pilotBoardingPlace:z.string().trim().max(160).default(""), notes: z.string().trim().max(1000).default(""), acceptedPolicy: z.literal("on") });

type ReportRow=typeof reports.$inferSelect;
function toMinutes(value:string){return Date.parse(`${value}Z`)/60000}
function fromMinutes(value:number){return new Date(value*60000).toISOString().slice(0,16)}
function median(values:number[]){const sorted=[...values].sort((a,b)=>a-b);const middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]:Math.round((sorted[middle-1]+sorted[middle])/2)}
function toleranceFor(eventType:string){return eventType.startsWith("Cargo ")||eventType==="Vessel Ready to Sail"||eventType==="Gangway Down"?10:5}
function validImo(imo:string){const digits=imo.replace(/^IMO\s*/i,"");return digits.length===7&&digits.slice(0,6).split("").reduce((sum,digit,index)=>sum+Number(digit)*(7-index),0)%10===Number(digits[6])}

function consensusReports(rows:ReportRow[],viewerUserId:string|null){
 rows=rows.map(row=>row.eventType==="Pilot Away"?{...row,eventType:"Pilot Off"}:row);
 const groups=new Map<string,ReportRow[]>();
 for(const row of rows){const callId=row.portCallId||`legacy:${row.imo}|${row.portCode}`;const key=`${callId}|${row.eventType}|${row.timeBasis}`;groups.set(key,[...(groups.get(key)??[]),row])}
 const output=[];
 for(const group of groups.values()){
  const clusters:ReportRow[][]=[];
  for(const row of [...group].sort((a,b)=>a.eventTimeUtc.localeCompare(b.eventTimeUtc))){const time=toMinutes(row.eventTimeUtc);const current=clusters.at(-1);const currentMedian=current?median(current.map(x=>toMinutes(x.eventTimeUtc))):0;if(current&&Math.abs(time-currentMedian)<=toleranceFor(row.eventType))current.push(row);else clusters.push([row])}
  for(const cluster of clusters){
   const unique=new Map<string,ReportRow>();for(const row of cluster){const source=row.reporterUserId??`report-${row.id}`;const existing=unique.get(source);if(!existing||row.createdAt>existing.createdAt)unique.set(source,row)}
   const selected=[...unique.values()];const verified=selected.filter(x=>x.status==="verified");const displayRows=verified.length?verified:selected;const times=displayRows.map(x=>toMinutes(x.eventTimeUtc));const first=displayRows[0];const own=viewerUserId?selected.find(x=>x.reporterUserId===viewerUserId&&x.status==="pending"):undefined;const consensusUtc=fromMinutes(median(times));const spread=Math.max(...times)-Math.min(...times);
   output.push({id:first.id,ownReportId:own?.id,portCallId:first.portCallId||`legacy:${first.imo}|${first.portCode}`,vesselName:first.vesselName,imo:first.imo,portCode:first.portCode,eventType:first.eventType,eventTimeUtc:consensusUtc,eventTimeOriginal:first.eventTimeOriginal||first.eventTimeUtc,timeReference:first.timeReference||"utc",portTimezone:first.portTimezone||portTimezones[first.portCode]?.timezone||"",timeBasis:first.timeBasis,terminal:first.terminal,berth:first.berth,pilotBoardingPlace:first.pilotBoardingPlace,status:verified.length?"verified":"pending",createdAt:first.createdAt,independentSources:selected.length,timeSpreadMinutes:spread,corroborated:selected.length>=2&&spread<=toleranceFor(first.eventType)})
  }
 }
 return output.sort((a,b)=>b.eventTimeUtc.localeCompare(a.eventTimeUtc)).slice(0,200)
}

export async function GET(){const viewer=await getChatGPTUser();const rows=await getDb().select().from(reports).where(and(notInArray(reports.status,["rejected","superseded"]),eq(reports.visibility,"public"))).orderBy(desc(reports.eventTimeUtc)).limit(500);return Response.json({reports:consensusReports(rows,viewer?.userId??null)},{headers:{"cache-control":"no-store"}})}
export async function POST(request:Request){if(!sameOrigin(request))return Response.json({error:"Invalid request origin"},{status:403});const user=await getChatGPTUser();if(!user)return Response.json({error:"Sign in to submit a professional report"},{status:401});const reporterUserId=user.userId;const parsed=reportSchema.safeParse(await request.json());if(!parsed.success)return Response.json({error:"Check the required report fields",issues:parsed.error.flatten()},{status:400});const{acceptedPolicy:_,...data}=parsed.data;void _;if(!catalogTimezones.has(data.portCode))return Response.json({error:"Select a port from the official UN/LOCODE directory"},{status:400});const portTimezone=catalogTimezones.get(data.portCode)??"";if(data.portTimezone!==portTimezone)return Response.json({error:"The selected port time zone could not be verified"},{status:400});if(data.timeReference==="port_local"&&!isValidTimezone(portTimezone))return Response.json({error:"Port Local Time is unavailable for this location. Select UTC."},{status:400});const calculatedUtc=data.timeReference==="utc"?data.eventTimeOriginal:localTimeToUtc(data.eventTimeOriginal,portTimezone);if(!calculatedUtc||calculatedUtc!==data.eventTimeUtc)return Response.json({error:"The time conversion could not be verified. Check the time reference and port time zone."},{status:400});data.portTimezone=portTimezone;data.eventTimeUtc=calculatedUtc;const imo=data.imo.replace(/^IMO\s*/i,"");if(!validImo(imo))return Response.json({error:"Enter a valid IMO number, including its check digit"},{status:400});const eventDate=new Date(`${data.eventTimeUtc}Z`);const now=Date.now();if(eventDate.getTime()<now-30*86400000||eventDate.getTime()>now+14*86400000)return Response.json({error:"Event time must be within the last 30 days or next 14 days"},{status:400});const db=getDb();const tenMinutesAgo=new Date(now-600000).toISOString();const[activity]=await db.select({count:sql<number>`count(*)`}).from(reports).where(and(eq(reports.reporterUserId,reporterUserId),gte(reports.createdAt,tenMinutesAgo)));if(Number(activity?.count??0)>=30)return Response.json({error:"Submission limit reached. Please try again shortly."},{status:429});const cutoff=new Date(eventDate);cutoff.setHours(cutoff.getHours()-48);const[recent]=await db.select({portCallId:reports.portCallId}).from(reports).where(and(eq(reports.imo,imo),eq(reports.portCode,data.portCode),gte(reports.eventTimeUtc,cutoff.toISOString().slice(0,16)))).orderBy(desc(reports.eventTimeUtc)).limit(1);const portCallId=recent?.portCallId||crypto.randomUUID();const[report]=await db.insert(reports).values({...data,imo,portCallId,reporterUserId,reporterEmail:user.email}).returning();return Response.json({report},{status:201})}
export async function PATCH(request:Request){if(!sameOrigin(request))return Response.json({error:"Invalid request origin"},{status:403});const user=await getChatGPTUser();if(!user||!isVHF14Admin(user))return Response.json({error:"Administrator access required"},{status:403});const reviewer=user.userId;const payload=z.object({id:z.number().int().positive(),status:z.enum(["verified","rejected"])}).safeParse(await request.json());if(!payload.success)return Response.json({error:"Invalid review"},{status:400});const db=getDb();const[previous]=await db.select().from(reports).where(eq(reports.id,payload.data.id)).limit(1);if(!previous)return Response.json({error:"Report not found"},{status:404});const[report]=await db.update(reports).set({status:payload.data.status,reviewedBy:reviewer,reviewedAt:new Date().toISOString()}).where(eq(reports.id,payload.data.id)).returning();if(payload.data.status==="verified"&&previous.status!=="verified"&&previous.reporterUserId){await db.insert(contributionCredits).values({userId:previous.reporterUserId,reportId:previous.id}).onConflictDoNothing()}else if(payload.data.status==="rejected"&&previous.status==="verified"){await db.delete(contributionCredits).where(eq(contributionCredits.reportId,previous.id))}return Response.json({report,creditAwarded:payload.data.status==="verified"&&previous.status!=="verified"&&Boolean(previous.reporterUserId)})}
