import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "../../../db";
import { reportCorrections, reportRevisions, reports } from "../../../db/schema";
import { getChatGPTUser } from "../../chatgpt-auth";
import { portTimezones } from "../../../lib/port-time";

const fields=z.object({vesselName:z.string().trim().min(2).max(100),imo:z.string().trim().regex(/^\d{7}$/),portCode:z.string().trim().toUpperCase().regex(/^[A-Z]{2}[A-Z0-9]{3}$/),eventType:z.enum(["Anchor Dropped","Anchor Aweigh","Pilot on Board","Tugs Connected","First Line","All Fast","Gangway Down","Cargo Operations Started","Cargo Operations Completed","Vessel Ready to Sail","Shifting Started","Shifting Completed","Last Line","Pilot Off","Port Clear"]),eventTimeUtc:z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/),timeBasis:z.enum(["actual","estimated","planned"]),sourceRole:z.enum(["VTS operator","Port professional","Pilot","Master / Bridge","Terminal operator","Tug crew","Mooring crew","Ship agent"]),reportingCapacity:z.enum(["personal","organisation"]),organisation:z.string().trim().max(150),terminal:z.string().trim().max(120).optional(),berth:z.string().trim().max(120).optional(),pilotBoardingPlace:z.string().trim().max(160).optional(),notes:z.string().trim().max(1000)});
const payload=z.discriminatedUnion("action",[z.object({action:z.literal("edit"),id:z.number().int().positive(),data:fields}),z.object({action:z.literal("quick_edit"),id:z.number().int().positive(),eventTimeUtc:z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/),eventTimeOriginal:z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/),timeReference:z.enum(["port_local","utc"]),timeBasis:z.enum(["actual","estimated","planned"])}),z.object({action:z.literal("withdraw"),id:z.number().int().positive()}),z.object({action:z.literal("request_correction"),id:z.number().int().positive(),reason:z.string().trim().min(5).max(500),data:fields})]);
function validImo(imo:string){return imo.length===7&&imo.slice(0,6).split("").reduce((sum,digit,index)=>sum+Number(digit)*(7-index),0)%10===Number(imo[6])}
function validTime(value:string){const time=Date.parse(`${value}Z`);return Number.isFinite(time)&&time>=Date.now()-30*86400000&&time<=Date.now()+14*86400000}

export async function PATCH(request:Request){
 const user=await getChatGPTUser();if(!user)return Response.json({error:"Authentication required"},{status:401});const parsed=payload.safeParse(await request.json());if(!parsed.success)return Response.json({error:"Check the report details"},{status:400});
 const db=getDb();const [report]=await db.select().from(reports).where(and(eq(reports.id,parsed.data.id),eq(reports.reporterUserId,user.userId))).limit(1);if(!report)return Response.json({error:"Report not found"},{status:404});
 if(parsed.data.action==="withdraw"){if(report.status!=="pending")return Response.json({error:"Verified reports require a correction request"},{status:409});await db.insert(reportRevisions).values({reportId:report.id,actorUserId:user.userId,action:"withdrawn",previousData:JSON.stringify(report)});await db.update(reports).set({status:"rejected",reviewedBy:user.userId,reviewedAt:new Date().toISOString()}).where(eq(reports.id,report.id));return Response.json({ok:true});}
 if(parsed.data.action==="quick_edit"){if(report.status!=="pending")return Response.json({error:"This report has already been reviewed. Request a correction instead."},{status:409});if(!validTime(parsed.data.eventTimeUtc))return Response.json({error:"Event time must be within the last 30 days or next 14 days"},{status:400});const next={...report,eventTimeUtc:parsed.data.eventTimeUtc,eventTimeOriginal:parsed.data.eventTimeOriginal,timeReference:parsed.data.timeReference,timeBasis:parsed.data.timeBasis,reviewedBy:null,reviewedAt:null};await db.insert(reportRevisions).values({reportId:report.id,actorUserId:user.userId,action:"edited",previousData:JSON.stringify(report),newData:JSON.stringify(next)});await db.update(reports).set({eventTimeUtc:parsed.data.eventTimeUtc,eventTimeOriginal:parsed.data.eventTimeOriginal,timeReference:parsed.data.timeReference,timeBasis:parsed.data.timeBasis,reviewedBy:null,reviewedAt:null}).where(eq(reports.id,report.id));return Response.json({ok:true});}
 const data=parsed.data.data;if(!validImo(data.imo))return Response.json({error:"Enter a valid IMO number"},{status:400});if(!validTime(data.eventTimeUtc))return Response.json({error:"Event time must be within the last 30 days or next 14 days"},{status:400});
 if(parsed.data.action==="edit"){if(report.status!=="pending")return Response.json({error:"This report has already been reviewed. Request a correction instead."},{status:409});const portCallId=report.imo===data.imo&&report.portCode===data.portCode?report.portCallId:crypto.randomUUID();const next={...report,...data,eventTimeOriginal:data.eventTimeUtc,timeReference:"utc" as const,portTimezone:portTimezones[data.portCode]?.timezone??report.portTimezone,portCallId,reviewedBy:null,reviewedAt:null};await db.insert(reportRevisions).values({reportId:report.id,actorUserId:user.userId,action:"edited",previousData:JSON.stringify(report),newData:JSON.stringify(next)});await db.update(reports).set({...data,eventTimeOriginal:data.eventTimeUtc,timeReference:"utc",portTimezone:next.portTimezone,portCallId,reviewedBy:null,reviewedAt:null}).where(eq(reports.id,report.id));return Response.json({ok:true});}
 if(report.status!=="verified")return Response.json({error:"Only verified reports need a correction request"},{status:409});const [existing]=await db.select().from(reportCorrections).where(and(eq(reportCorrections.reportId,report.id),eq(reportCorrections.requesterUserId,user.userId),eq(reportCorrections.status,"pending"))).limit(1);if(existing)return Response.json({error:"A correction request is already pending"},{status:409});await db.insert(reportCorrections).values({reportId:report.id,requesterUserId:user.userId,proposedData:JSON.stringify(data),reason:parsed.data.reason});return Response.json({ok:true});
}
